# Generated by Django 2.2.12 on 2020-12-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='catimage',
            field=models.ImageField(default=1, upload_to='catphotos'),
            preserve_default=False,
        ),
    ]
