# Generated by Django 2.2.12 on 2020-12-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201206_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='added_date',
        ),
    ]
