# Generated by Django 2.2.12 on 2020-12-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='usercat',
        ),
    ]
