# Generated by Django 2.2.12 on 2020-12-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201226_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='usercat',
        ),
    ]
