# Generated by Django 2.2.12 on 2020-12-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_image_imguser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imguser',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
