# Generated by Django 2.2.12 on 2020-12-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201227_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='catimage',
        ),
    ]
